services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shef-lms-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://shef-lms-mongo:27017/shef-lms
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - shef-lms-network

  mongo:
    image: mongo:6
    container_name: shef-lms-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - shef-lms-network

networks:
  shef-lms-network:
    driver: bridge
